### ISSUE TITLE
Linux. No video in version 1.20

### ISSUE THREAD

**Issue by themaximax** [jaruba/PowderPlayer#137] opened 2018-05-01 22:30 UTC
Good afternoon. 
After upgrading to version 1.20 there was a problem - there is no video in the built-in player (sound works)
In version 1.1 and older all worked well.
If you select VLC as the external player, it plays everything.
I tried to delete configs and a cache from the old version before "installation" new version of the player, but result the same.

> Sytem:
> OS: Ubuntu 16.04 xenial
> Kernel: x86_64 Linux 4.13.0-39-generic
> CPU: Intel Core i5-4670 CPU @ 3.8GHz

**Comment by jaruba** [comment] 2018-05-03 16:52
I've tested it on Ubuntu before release and it worked for me, I did change the Electron version before releasing, that might be at fault. As soon as I have anything conclusive regarding this issue I'll write back.

**Comment by YegorKh** [comment] 2018-07-01 12:06
In 1.20 (1.20-1 from AUR) I also got no video, but sound doesn't work too. Only black screen. 

Sometimes after I enter dev tools - it start work well, sometimes not.

I was try select VLC as external player, but I got no readable fonts in settings

System: Linux 4.14.48-2-MANJARO #1 SMP PREEMPT Fri Jun 8 20:41:40 UTC 2018 x86_64 GNU/Linux

**Comment by YegorKh** [comment] 2018-09-03 21:33
@jaruba any suggestions?

**Comment by jaruba** [comment] 2018-09-04 06:53
Not really, i'll try to release a new version soon that should fix the issue.

I think the problem is that in the latest version I packaged the app with a newer Electron version that's incompatible with WebChimera.js (the part that connects to libVLC) and thus breaks the app completely on some Linux systems.

Plans are to remove WebChimera.js from the player as it's already deprecated and forces using old tech. I'll try to make the player use MPV instead of libVLC. There are also plans to moving the engine (torrent and other protocol support) to [Powder Web](https://github.com/jaruba/PowderWeb), this will enable extra features in the player such as:
- acestream and sopcast support
- a torrent manager that will act as a service (with an icon in the tray)
- a complete web manager (stream your entire catalog to any device in your house or even through the internet)
- and many other new features

All this will take some time to do, but will guarantee an awesome and unbreakable Linux version in the future. I'll try to release a fast version first that fixes Linux and subtitles which seem to be the biggest issues in the latest version.

My suggestion is that you use v1.10 if that worked for you well until a newer version comes out. Sorry for any inconvenience this may have caused.

**Comment by jaruba** [comment] 2018-09-05 22:50
I found the reason for this issue, new version coming soon.

**Comment by YegorKh** [comment] 2018-09-09 17:21
@jaruba thank's a lot for response. Waiting for new version...

**Comment by jaruba** [comment] 2020-01-20 02:44
Please try the latest release of Powder Player: https://powder.media/download

I'll close this issue in the meanwhile, if you still have issues you can reopen it.

**Closed as completed by jaruba** 2020-01-20 02:44 UTC
