### ISSUE TITLE
Error in DLNA Mode: Cannot read property 'mrl' of undefined

### ISSUE THREAD

**Issue by MarcWH** [jaruba/PowderPlayer#66] opened 2015-11-25 20:12 UTC
I am running Powder Player in dlna mode from a Mac OS 10.10.5 and I get the following error when scanning for the dlna device.

Any idea?

[25742:1125/211102:ERROR:nw_shell.cc(336)] TypeError: Cannot read property 'mrl' of undefined
    at prepareDlnaServer (app://powder/src/lib/dlna.js:208:49)
    at app://powder/src/lib/dlna.js:376:4
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:80:10)
[25742:1125/211102:INFO:CONSOLE(208)] "Uncaught TypeError: Cannot read property 'mrl' of undefined", source: app://powder/src/lib/dlna.js (208

**Comment by MarcWH** [comment] 2015-11-25 20:13
.. and btw, thanks for this great peace of open source software!

**Comment by jaruba** [comment] 2015-11-25 20:14
uhm, what are you trying to stream through dlna? a torrent or something else?

**Comment by MarcWH** [comment] 2015-11-25 20:24
well, the error comes when I hit "Stream to TV" and the app is "Searching for Device".
Also after hitting "Rescan"

I tried torrent and local avi, but it does not seem to be related to that

**Comment by jaruba** [comment] 2015-11-25 20:25
Uhm, what brand of TV do you have?

**Comment by MarcWH** [comment] 2015-11-25 20:33
Sony kdl-37ex500 

I confirmed that DLNA is working on the TV with Serviio

**Comment by Ivshti** [comment] 2015-11-26 08:04
@jaruba do you think we can somehow re-use what serviio has - by doing an integration with them or by using a source code if they're open source?

**Comment by luigiplr** [comment] 2015-11-26 08:06
Why do i get the feeling there not open source.

**Comment by jaruba** [comment] 2015-11-26 08:07
@Ivshti their not open source.. as their selling the Pro version.

**Comment by luigiplr** [comment] 2015-11-26 08:07
Called it now where be my :melon:

**Comment by Ivshti** [comment] 2015-11-26 08:11
You guys are apparently online now.

Too bad, stuff like casting should be open-source for humanitarian reasons - reduce suffering.

@luigiplr what's that melon? :boar:

**Comment by jaruba** [comment] 2015-11-26 08:12
I think @MarcWH is experiencing an issue i already fixed at one point but isn't in the last release. There's a lot of work to be done on DLNA and frankly i'd throw my current DLNA code out the window as this needs a more serious approach..

**Comment by jaruba** [comment] 2015-11-26 08:15
> Too bad, stuff like casting should be open-source for humanitarian reasons - reduce suffering.

@Ivshti **make the repo!**

![fulfill-your-destiny](https://cloud.githubusercontent.com/assets/1777923/11418215/aa6dad48-9426-11e5-8188-89df09805e26.jpg)

**Comment by Ivshti** [comment] 2015-11-26 08:19
@jaruba I thought about it.

I thought about using mafintosh/multicast-dns and node-ssdp for discovery in the same module.

From then, using node-upnp-mediarenderer-client + butter's custom meta building for DLNA,
node-castv2 for Chromecast for chromecast,
and rip the core from node-airplay but rework it over multicast-dns discovery to do Airplay

What are the issues with this approach? Well:

1. multicast-dns doesn't have service discovery, I'll have to implement that
2. people are unhappy with node-ssdp for some reason ; nodecast-js's ssdp seems a bit spaghetti though :(
3. re-implementing the same that mafintosh/chromecasts does. I don't want to do something that mafintosh does, since he probably did it very well

And that's the best thing I figured out. Any ideas/feedback?

**Comment by jaruba** [comment] 2015-11-26 08:22
`node-ssdp` is shit..

@vankasteelj recommended `nodecast-js` for discovery :melon:

**Comment by jaruba** [comment] 2015-11-26 08:23
even posted proof: https://github.com/jaruba/PowderPlayer/issues/51#issuecomment-158266350

**Comment by Ivshti** [comment] 2015-11-26 08:23
Then it's probably a good idea to rip the ssdp code from nodecast-js and create a module like ssdp-js. node-ssdp is also pure js, excluding the tracing, but in order to avoid name collision we can use ssdp-js

The issue is I don't understand a bit about ssdp, so if I probably look at nodecast-js / node-ssdp sources I won't be able to tell why the one is labeled as shit and the other works

**Comment by jaruba** [comment] 2015-11-26 08:28
It may be that `node-ssdp` works good enough and i just didn't search for all the necessary schemas, but even on the TVs i tested DLNA on, `node-ssdp` never finds them 100% of the times. It fails a lot, can't be sure if this is a TV issue or module issue though, I just know that inserting the URL directly works when `node-ssdp` doesn't find anything.

**Comment by luigiplr** [comment] 2015-11-26 08:37
@Ivshti you also need relevant headers in your stream server

**Comment by Ivshti** [comment] 2015-11-26 08:47
I know, I have those for the video - I am asking for the art

**Comment by jaruba** [comment] 2016-01-03 23:06
I think this specific error has been fixed in the latest version, if you still have this error, please reopen the ticket.

**Closed by jaruba** 2016-01-03 23:06 UTC

**Comment by luigiplr** [comment] 2016-01-03 23:20
>I **think** this specific error has been fixed

![](http://ci.memecdn.com/174/1344174.jpg)
