### ISSUE TITLE
powder isue 

### ISSUE THREAD

**Issue by kvirusp** [jaruba/PowderPlayer#6] opened 2015-03-06 20:50 UTC
after watching a local video i click exit to main menu and then drag and drop another file.
the new file only plays audio, video being replaced by prebuffering icon

**Comment by jaruba** [comment] 2015-03-06 20:54
This is a duplicate of: https://github.com/jaruba/PowderPlayer/issues/7

**Closed** 2015-03-06 20:55 UTC
Labels: duplicate

**Comment by kvirusp** [comment] 2015-03-06 21:03
yeah but it's really annoying
