### ISSUE TITLE
Pausing/rewinding etc. causes crash

### ISSUE THREAD

**Issue by PeterPerraPezzon** [jaruba/PowderPlayer#145] opened 2018-10-12 19:48 UTC
So, in essence doing anything to the progress of the video stalls the player completely.
moving the progress bar to fast forward/rewind, or pausing the video for more than just a short while will result in me not being able to restart the video...
The player reacts when I click (both on screen and the play button) but nothing happens.
Only thing to do is shut down, and reload the torrent.

Does anyone have a fix for this?

**Comment by jaruba** [comment] 2018-10-12 19:51
what OS are you using? is the file you're playing from the torrent an mp4 file? (check Torrent Data in the right click menu)

**Comment by PeterPerraPezzon** [comment] 2018-10-12 19:55
I'm running windows 10, the current torrent is an avi file, but I'm having this issue with every file. I'm currently on my laptop, but I had this problem on my desktop (also win 10) as well

**Comment by jaruba** [comment] 2018-10-12 19:58
what does "pausing the video for more then just a short while" mean? closing the laptop lid and leaving it for a few hours? or your pc completely running (not hibernating / logged off / in sleep mode) for 15 minutes?

Such details are important.

**Comment by PeterPerraPezzon** [comment] 2018-10-12 20:02
no nothing like that, I've tried hitting pause and then immediately resuming (within a second) and that doesn't cause it to stop. But anything more than a few seconds (paused it to go get a soda from the fridge, so, 30 seconds?) will cause the error.
Trying to rewind or forward in any way also causes the same error, even after the torrents finished downloading

**Comment by jaruba** [comment] 2018-10-12 20:09
that's fucked up, i don't see how that could happen. is it possible you only tried to stream "old" torrents? avi was extremely popular (a lot of) years ago, but no one uses it anymore. if you only tried "old" torrents, then it's possible they were all avi files and this is an avi file issue.

**Comment by PeterPerraPezzon** [comment] 2018-10-12 20:18
it's "a quiet place" so the torrent is only days old.
I have no idea what's going on either, I haven't been able to find any answers anywhere, which sucks because I like powder player otherwise. Hopefully it will go away equally inexplicably with the next update

**Comment by jaruba** [comment] 2018-10-12 20:22
well i'm planning a new update, just didn't get around to it, still, if you say the player plays the video, then stops randomly after 30 seconds of pausing, i've never experienced something like that. mp4 has some issues, but never all the video types..

It's hard to understand what the issue is, but it's not the pausing..

**Comment by PeterPerraPezzon** [comment] 2018-10-12 20:23
I wish I had more knowledge about this subject, perhaps I could be of more help. but that's all I can really add

**Comment by jaruba** [comment] 2018-10-12 20:31
Three crazy things i would try when it's frozen:
- right click on the player -> Torrent Data -> click gear icon in the upper right corner -> go to player (this should restart the player and seek to the old position, does it play after this?)
- right click -> Torrent Data -> Click video file -> Play Now
- right click -> Torrent Data -> Open Containing Folder -> run the video with any video player (even Powder Player again)

Does it work if you try to trick it in any of these ways? If so, which of them?

**Comment by lalibi** [comment] 2019-04-20 10:42
I have the exact same issue on Win 10, and I narrowed it down to this. The controls, e.g. pause/play, cause the player to freeze up, but only after the video has finished downloading. I've tried it many times and it's always the same behavior.

While the video is being downloaded everything works as expected. Another thing I noticed is this. If the `.torrent` file contains multiple video files, and I'm watching, for instance, the first one, If I try to pause, or go back and forward (only after the file is complete), with either the mouse or the keyboard, the player goes to the next file on the playlist.

**Comment by jaruba** [comment] 2019-04-21 07:29
I think I found the reason for this bug, it will be fixed in the next release. I'm just uncertain when I'll have time to release it.

**Comment by lalibi** [comment] 2019-04-21 18:47
Nice to hear, looking forward to the release!

**Comment by shamilovtim** [comment] 2019-12-31 04:33
Still experiencing this issue on macOS

**Comment by jaruba** [comment] 2020-01-03 18:34
@shamilovtim @lalibi 

I've made a test version for OSX and Win, please test it asap against this bug.. We need to make sure this bug is gone for good before I release.

You can download it here:
https://github.com/jaruba/PowderPlayer-Test/releases/tag/v0.0.1

**Comment by lalibi** [comment] 2020-01-04 10:12
Unfortunately, it didn't work in my system. The behavior was the same, as soon as the torrent is complete, play/pause e.t.c. functions cause to video to freeze up and be unresponsive (black screen).

Win 10 Pro x64 (v 1909)

**Comment by jaruba** [comment] 2020-01-04 10:16
@lalibi

Can you please send me the torrent or magnet you tried with on my email? (my email is visible on my github profile)

**Comment by lalibi** [comment] 2020-01-04 10:37
It is the same behavior with any torrent really.

I just tried it with https://webtorrent.io/torrents/sintel.torrent (which is a free movie)

**Comment by jaruba** [comment] 2020-01-04 11:06
@lalibi I know this happened for all torrents, but I can't for the life of me reproduce it on Win 10 x64 anymore (tried the Sintel torrent too), even on the old version of Powder Player.. I'll try other Operating Systems..

**Comment by jaruba** [comment] 2020-01-04 11:40
@lalibi Ok, I've reproduced it on OSX, it does indeed happen in the last version too. I'll try to make a new test version once I figure out why the last possible fix didn't work.

**Comment by lalibi** [comment] 2020-01-04 12:09
@jaruba Not sure if this screen grab helps -> https://www.dropbox.com/s/xbca8l527vvqqf0/grab.avi?dl=0

Seeking has issues (just like the official v1.20 release), even before the torrent is complete, but after it's done it gets completely stuck.

I've tried several things, like going to "torrent data" and then back to the player, I even deleted the `Powder-Player` folder from `%AppData%`.

Is the `powder.exe` (in the win zip file) file supposed to be from `11/4/2018`? All other files have `LastWriteTIme = 3/1/2020`.

P.S. Really appreciate the time & effort you put into this, I hope I can help somehow to resolve this.

**Comment by jaruba** [comment] 2020-01-04 12:38
Yeah, `powder.exe` is supposed to be old, I switched it with the old executable to not need to change the icon to Powder's again. That shouldn't cause issues as they're the same Electron version.

Let me take you through the history of this hellish bug.

The usual seeking issues are due to a bug in the VLC engine that is used, there's logic to correct it in most cases, but it can still fail rarely. It shouldn't ever be critical though.

As for playback getting completely stuck after download ends, I fought with this bug a lot a year ago. The bug made no sense, the torrent engine would just die out inexplicably after the download finished, and that would obviously kill playback too.

The bug was present in both Powder Player and Powder Web, that both used a highly customized torrent engine that I worked on heavily. Finally, in last year's team building, me and some of the top minds at Stremio all fought with it and couldn't figure out why it would ever happen.

We eventually concluded that the issue must come from forking the Electron process. I then continued testing tens of Electron versions and they all showed the same symptoms. So I moved the entire torrent engine into it's own binary, thus avoiding to fork Electron's process all together, and that completely fixed the issue in Powder Web. I continued to stress test Powder Web with the changes for a year after that, and it never happened again.

So I added the new changes to the torrent engine in Powder Player too recently in the test release I posted. While making the changes I tried testing against the bug on Win 10 x64, but I was unable to reproduce it with either the old or the new test version.

I'm able to reproduce it now on OSX with both the old and the test version, but I'm at a complete loss of how it could continue to happen with the new torrent engine.

I'll keep hitting it with my dev hammer to see if I can make any progress on this.

**Comment by jaruba** [comment] 2020-01-04 14:35
I'm shocked to say that this is not the initial bug.. that bug was indeed fixed with the new torrent engine, the torrent engine doesn't die out anymore, there is something in the player logic that is causing this now.

I'm definitely making progress, and I think I know what might be causing this too.

**Comment by jaruba** [comment] 2020-01-04 15:33
Ok, I think I fixed it this time.

@shamilovtim @lalibi Please confirm that the bug is gone in this test version:
https://github.com/jaruba/PowderPlayer-Test/releases/tag/v0.0.2

**Comment by jaruba** [comment] 2020-01-04 15:39
@lalibi 

Also, worth mentioning, after the download ends for the current playing file, ALL seeking issues should be completely fixed for that video. (instead of the playback simply exploding like before..)

To clarify, this last bug regarding this issue was specific to not having a download folder set. It only happened if the download folder was "Temp". (which is the default)

**Comment by shamilovtim** [comment] 2020-01-04 16:38
I don't think it relates to VLC personally. I started using VLC instead to skip / pause / start and those functions work fine in VLC.

**Comment by jaruba** [comment] 2020-01-04 16:46
@shamilovtim

Yes, they work well now, but this project uses a particular version of VLC that did not have all these streaming issues fixed, and we are stuck at that version due to WebChimera.js limitations.

The plan (in the long run) is for Powder Player to merge with Powder Web. Becoming an all-in-one solution that additionally supports AceStream, SopCast, and a lot more other protocols too, and switch to using a skinned MPV instead of VLC.

**Comment by jaruba** [comment] 2020-01-04 16:49
@shamilovtim Please also test (at your earliest convenience) the version I last linked against this bug. It's important we all agree that this white whale is dead.

**Comment by shamilovtim** [comment] 2020-01-04 16:50
Why not just add an "open in VLC" setting for now and make it default? It will make the player still the point of contact for users for streaming and they can eject back to the WebChimera.js player as a fallback if they need it, until a better custom player takes its place.

**Comment by jaruba** [comment] 2020-01-04 16:53
@shamilovtim Check the "Media Handling" settings, you can already choose a default player and command line arguments for it if you want.

Powder Player has a ton of settings you might not know of. :)

**Comment by shamilovtim** [comment] 2020-01-04 16:55
I didn't mean for me actually I'm very comfortable with the CLI, I just meant having that be the default for the general public. Would it make sense to have to have it default to VLC until the custom player is up to par?

**Comment by shamilovtim** [comment] 2020-01-04 17:07
I can't get the latest version to stream at all. It stays stuck on "processing URL" after using a magnet link

**Comment by jaruba** [comment] 2020-01-04 17:27
@shamilovtim I've updated the release with a new build:
https://github.com/jaruba/PowderPlayer-Test/releases/tag/v0.0.2

It should work now, please test. The reason I'm not just running VLC instead of the internal player is because Powder Player is ultimately a Player. It can have some issues, sure, but this bug is quite literally the one real problem with it.

**Comment by lalibi** [comment] 2020-01-04 18:03
> Let me take you through the history of this hellish bug.

That is harsh, as a developer myself I really feel you. I'm glad you've figured it out...

> Please confirm that the bug is gone in this test version

... because I think you actually did! I've tested 3 different torrents with the latest test version and my findings are the following:

- The total freeze up, after the torrent has completed, is gone!
- Seeking is still wonky in one of those I tried (actually it was the "sintel" one I posted earlier). _Sometimes_, clicking on the timeline results in resetting the playback to the begging of the video. "Funny" thing is that this happens _only_ while the torrent is downloading. After it's complete, everything seems fine. It's probably not a big issue, the video recovers when you click elsewhere in the timeline, but I thought I should mention it.

I'll be logging one or two more issues I've found, but, again, I'm really glad the main issue has been resolved. Thank you again for your time.

**Comment by jaruba** [comment] 2020-01-04 18:18
@lalibi That's what I want to hear!

> "Funny" thing is that this happens only while the torrent is downloading.

Not when the torrent is downloading, when the torrent file is downloading. And yes, when the torrent file has finished downloading, all VLC http stream playback issues dissapear, as we start using the local video file instead of streaming it! That's what was supposed to happen all along.. actually..

**Comment by jaruba** [comment] 2020-01-20 02:37
Please try the latest release of Powder Player: https://powder.media/download

I'll close this issue in the meanwhile, if you still have issues you can reopen it.

**Closed as completed by jaruba** 2020-01-20 02:37 UTC
